#!/bin/bash

#PBS -q standard
#PBS -W group_list=<GROUP NAME>

#PBS -N Sample_Parallel_Job

#PBS -l select=1:ncpus=28:mem=168gb:pcmem=6gb
#PBS -l walltime=00:02:00

# Load GNU parallel so we can execute multiple tasks
module load parallel

cd $PBS_O_WORKDIR

# Executing 100 tasks in parallel. See Walkthrough for more information.
seq 1 100 | parallel 'DATE=$( date +"%T" ) && sleep 0.{} && echo "Host: $HOSTNAME ; Date: $DATE; {}"'
